### ISSUE TITLE
go get fails to install

### ISSUE THREAD

**Issue by richp10** [williammoran/expiringlink#2]
go get github.com/williammoran/expiringlink
go: downloading github.com/williammoran/expiringlink v0.0.0-20211030111254-a595d5c2a743
go get: github.com/williammoran/expiringlink@v0.0.0-20211030111254-a595d5c2a743: parsing go.mod:
        module declares its path as: potentialtech.com/expiringlink
                but was required as: github.com/williammoran/expiringlink

I think you need to change go.mod to reference the github location?

**Comment by williammoran** [comment]
Fixed. Thanks for the report!

**Comment by richp10** [comment]
Works now thanks...
